name: Daily Rebuild

on:
  schedule:
    - cron: '0 17 * * *' # Everyday at noon (UTC time)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build your project
        run: |
          npm install
          npm run build
